-   id: pydoclint
    name: pydoclint
    description: pydoclint is a static analysis tool for checking compliance with Python docstring conventions.
    entry: pydoclint
    language: python
    types: [python]
